### ISSUE TITLE
Error when running kong/httpbin:0.2.0

### ISSUE THREAD

**Issue by MattiasGees** [Kong/httpbin#60]
Hi,

The latest release of httpbin broke the image. When I now try to start running it I get the following error:

```
gunicorn": executable file not found in $PATH: unknown
```

**Comment by pmalek** [comment]
I have tested and both 0.1.0 and 0.2.0 run without errors:

```
docker run -it --rm kong/httpbin:0.1.0
Unable to find image 'kong/httpbin:0.1.0' locally
0.1.0: Pulling from kong/httpbin
11e23ac719b3: Pull complete
48f131cc60da: Pull complete
a6f08b48d25e: Pull complete
4f4fb700ef54: Pull complete
1f743af032a3: Pull complete
2124c491461a: Pull complete
7042a0ef4f5e: Pull complete
Digest: sha256:b9bfd44e6aca835b6622fc0ebb03372792ac3fb5c36477c3c970691a7e30bb20
Status: Downloaded newer image for kong/httpbin:0.1.0
[2024-09-24 14:21:25 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2024-09-24 14:21:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-09-24 14:21:25 +0000] [1] [INFO] Using worker: gevent
```

```
docker run -it --rm kong/httpbin:0.2.0
Unable to find image 'kong/httpbin:0.2.0' locally
0.2.0: Pulling from kong/httpbin
e63ce922f022: Pull complete
35e7cfe3f2b2: Pull complete
50ec409c3c54: Pull complete
ce617194b43b: Pull complete
af2ee96c978a: Pull complete
Digest: sha256:c0c44152d0c9466915aaea170fd4dbe7a418829d7c479520407e4f2f9048a9aa
Status: Downloaded newer image for kong/httpbin:0.2.0
[2024-09-24 14:21:47 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-09-24 14:21:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-09-24 14:21:47 +0000] [1] [INFO] Using worker: gevent
[2024-09-24 14:21:47 +0000] [8] [INFO] Booting worker with pid: 8
^C[2024-09-24 14:21:53 +0000] [1] [INFO] Handling signal: int
[2024-09-24 14:21:53 +0000] [8] [INFO] Worker exiting (pid: 8)
[2024-09-24 14:21:53 +0000] [1] [INFO] Shutting down: Master
```

Can you share steps to reproduce?

**Comment by taer** [comment]
Just removed the command section from the launch, and here are the logs 
```
Creating a virtualenv for this project
Pipfile: /httpbin/Pipfile
Using default python from /usr/bin/python33.10.12 to create virtualenv...
created virtual environment CPython3.10.12.final.0-64 in 204ms
  creator CPython3Posix(dest=/tmp/httpbin-30d5U6R4, clear=False, 
no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, 
wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==24.2, setuptools==75.1.0, wheel==0.44.0
  activators 
BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator
,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /tmp/httpbin-30d5U6R4
Error: the command gunicorn could not be found within PATH or Pipfile's [scripts].
```

with 0.1.0
```
    spec:
      containers:
      - env:
        - name: WORKON_HOME
          value: /tmp
        image: docker.io/kong/httpbin:0.1.0
        imagePullPolicy: IfNotPresent
        name: httpbin
```
the logs are 
```
[2024-09-24 20:24:54 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2024-09-24 20:24:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-09-24 20:24:54 +0000] [1] [INFO] Using worker: gevent
/usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2024-09-24 20:24:54 +0000] [9] [INFO] Booting worker with pid: 9
```

**Comment by taer** [comment]
the command overrides were there to change the port to 8080

**Comment by taer** [comment]
I found it. I'm not sure why this is here(again, this is the deployment yaml from Istio), but this env var breaks it `WORKON_HOME=/tmp`

docker run -e WORKON_HOME=/tmp  --rm docker.io/kong/httpbin:0.2.0   <--- fails
docker run  --rm docker.io/kong/httpbin:0.2.0   <--- works

**Comment by demikl** [comment]
Same here, starting the container as non-root :

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - image: all-docker.artifact.cloud.socrate.vsct.fr/kong/httpbin
        name: httpbin
        securityContext:
          runAsUser: 1000
```

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/options.py", line 52, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/command.py", line 422, in run
    do_run(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/routines/shell.py", line 68, in do_run
    ensure_project(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/project.py", line 40, in ensure_project
    if project.s.PIPENV_USE_SYSTEM or project.virtualenv_exists:
  File "/usr/local/lib/python3.10/dist-packages/pipenv/project.py", line 418, in virtualenv_exists
    if os.path.exists(self.virtualenv_location):
  File "/usr/local/lib/python3.10/dist-packages/pipenv/project.py", line 606, in virtualenv_location
    self._virtualenv_location = self.get_location_for_virtualenv()
  File "/usr/local/lib/python3.10/dist-packages/pipenv/project.py", line 440, in get_location_for_virtualenv
    return str(get_workon_home().joinpath(self.virtualenv_name))
  File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/shell.py", line 196, in get_workon_home
    os.makedirs(expanded_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
Stream closed EOF for httpbin/httpbin-76cf96d9fd-mmd6c (httpbin)
```

**Comment by pmalek** [comment]
@demikl I've just tested and not specifying the user works well:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kong/httpbin:0.2.0
        name: httpbin
```

If you feel this can be improved to accommodate specifying the user please feel free to submit a PR. Having said that please bear in  mind that this is a different issue than the one we're discussing here so if you feel you'd like to take this forward consider creating a separate one.

**Comment by VBranimir** [comment]
> @demikl I've just tested and not specifying the user works well:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: httpbin
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: httpbin
>   template:
>     metadata:
>       labels:
>         app: httpbin
>     spec:
>       containers:
>       - image: kong/httpbin:0.2.0
>         name: httpbin
> ```
> 
> If you feel this can be improved to accommodate specifying the user please feel free to submit a PR. Having said that please bear in mind that this is a different issue than the one we're discussing here so if you feel you'd like to take this forward consider creating a separate one.

Reproduced problems from issue 60 and issue 62 and submitted a PR that enables usage of runAsUser :
https://github.com/Kong/httpbin/pull/63

BR, Branimir

**Comment by MarkusFlorian79** [comment]
I have the same problem running the image from docker.io. 

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown`

Running docker inspect on that image shows me:
`"Cmd": [
                "gunicorn",
                "-b",
                "0.0.0.0:8080",
                "httpbin:app",
                "-k",
                "gevent"
            ],
`
Running the gunicorn manually in the image fails as well. While running "pipenv run gunicorn ..." works.

Building the image locally and running docker describe shows me:
`"Cmd": [
                "pipenv",
                "run",
                "gunicorn",
                "-b",
                "0.0.0.0:80",
                "httpbin:app",
                "-k",
                "gevent"
            ],
`

Is it possible that the image on docker.io is build with the old Dockerfile using the cmd without pipenv?

**Comment by pmalek** [comment]
Hi @MarkusFlorian79 

I've just checked and 0.2.1 works well for me:

```
docker run -it --rm kong/httpbin:0.2.1
[2024-10-31 20:24:36 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-10-31 20:24:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-10-31 20:24:36 +0000] [1] [INFO] Using worker: gevent
[2024-10-31 20:24:36 +0000] [8] [INFO] Booting worker with pid: 8
```

The `Cmd` is set to what you described you also got when building locally.

```
docker inspect kong/httpbin:0.2.1 | jq '.[0].Config.Cmd'
[
  "pipenv",
  "run",
  "gunicorn",
  "-b",
  "0.0.0.0:80",
  "httpbin:app",
  "-k",
  "gevent"
]
```

**Comment by pmalek** [comment]
@VBranimir Can we close this one as #63 was merged?
